### ISSUE TITLE
Skill pools won't render

### ISSUE THREAD

**Issue by Cuboos** [Craftidore/Obsidian-Genesys#10]
So i've been wanting to run a game of SWRPG for a while now, i've used Obsidian in the past for D&D and fell in love with it instantly. I was excided when i saw there is a JASON and CSS for Genesys and SWRPG for the Fantasy Stats plug-in. However, no matter what I do, I can't get the dice pools to render. I even tried editing the JavaScript in the layout editor, to no avail. 

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/6ebd4da2-dcd8-4060-b0de-917f2c3de18e)

It's also having the same issue with rival and nemesis

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/d6a5a5f7-7edf-462e-b048-a1994ed36b41)
![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/797ae0fb-7d16-43a1-8ecb-005fb761398a)

**Comment by source-toad** [comment]
Nice one! Do you have the dice snippets installed and turned on? They work hand in hand with the statblock layouts.

**Comment by Cuboos** [comment]
I believe so, this is what you're referring too, right?

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/21ac5980-580f-49ef-938c-8e45e247d1a1)

**Comment by source-toad** [comment]
Hmm, and you've got the statblocks-essentials.css installed also?

The layout you've got above seems old. The newest statblock layout has a large header image, rather than the circular. It makes me think perhaps you've got an older version of the layout?

Try installed the latest Genesys.json statblock, along with statblock-essential.css and statblocks-swrpg-style.css (I tried to keep this styling separate and optional, but I didn't nail it, so it kind of needs both).

**Comment by Cuboos** [comment]
I have not, do you install that through the snippets panel?

**Comment by source-toad** [comment]
Yeah, install them the same way you installed the dice snippets. 

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/110574859/d0d0eda1-de40-4633-8059-bcdc44fda4f3)

Just to add to the list of things.. I have also set it up so you need to have ITS styled statblocks disabled in Style Settings.

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/110574859/b4b2a6c8-f927-4db9-a91f-6307e5105709)

**Comment by source-toad** [comment]
You should end up with something pretty like this: 

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/110574859/bd6a9759-c1f9-4477-b84d-bf76cd9c14a2)

**Comment by Cuboos** [comment]
![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/93e3d38e-85db-420a-942f-092db8c675cd)
![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/7611a505-9de5-48cc-b798-41b1014d06f0)
![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/1735d271-e718-41a7-bd20-fd66608b5131)

Still nothing. 

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/87bbbd3d-6d01-47ad-8d28-cbc053075a5c)


Here's a look at the YAML, is there something wrong here?

EDIT: sorry, didn't realize i posted the YALM twice.

**Comment by source-toad** [comment]
It could be that you've written null for the skills. Can you try putting 0? Its probably taking null as text, rather than true null, which is breaking the number calculations for qty of dice.

**Comment by Cuboos** [comment]
Still nothing i'm afraid.

**Comment by source-toad** [comment]
Do your tags work? Just like regular inline dice tags?

**Comment by Cuboos** [comment]
Yep, the tags work just fine. 
![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/b04ebb7a-0e2e-46c5-8ecf-ab7473a647e7)

**Comment by source-toad** [comment]
I think you might still have an older version of the statblock. Pre-restyling. Soak and wounds should look like this:

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/110574859/3f7193f4-52a4-45e0-be87-c0fad2db3a81)

Can you try re-adding the Genesys statblock from a freshdownload?

**Comment by Cuboos** [comment]
![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/a3b33377-673a-4030-b6cc-c484a764e592)

We're getting somewhere! It appears the links in the ReadMe are a bit out of date, downloading the more recent JASON brought it seems to have fixed it. My Icon may be a tad bit too big tho...

**Comment by source-toad** [comment]
Nice one, I will have to update the different bits and pieces so its clearer.

You might have to pick a banner style image haha. I tried to align it with how statblocks look in SWRPG source material.

**Comment by Cuboos** [comment]
Yes, I noticed that, and I actually appreciate it too. I was considering making PDFs of the NPC stats and embedding them, this plugin saves me a lot of time. So i HIGHLY appreciate you guys taking the time to make this. 

Although... is there a way to get more than three skills to appear? Also, I kinda prefer the more vertical style, is there an option to choose between single column and double column?

**Comment by Cuboos** [comment]
Okay i double-checked the documentation and i realized what i was doing wrong with the skills, all the skills show now. 

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/15208deb-4189-4751-8b73-e9b79f0797f1)
![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/5aa1fc76-121b-42f4-aee1-d9dd2d6ee1b4)
![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/cdf2b7ee-0d4c-4511-b302-72d7e513e554)

Alignments are still a bit wonky and awkward to look at, but this is otherwise functional.

**Comment by source-toad** [comment]
Yeah, I'm not a huge fan of how the double column chooses to split things up. But it just takes up so much less of the page haha.

If you want the single column, you just need to change the first line in the statblocks-essential.css from columns: 2  to 1.

**Comment by Cuboos** [comment]
I was afraid that was going to be the answer. 

Anyway, thanks for the answers!

**Comment by source-toad** [comment]
Its a pretty easy change, just open the css in a text editor.

![image](https://github.com/Craftidore/Obsidian-Genesys/assets/110574859/afb9b04f-e718-494e-a09d-c01a97b81111)

**Comment by Cuboos** [comment]
It worked, and it's virtually flawless now.
![image](https://github.com/Craftidore/Obsidian-Genesys/assets/8951668/c74536ca-12cf-45bf-90a2-329480a7ad23)

It's just... i've done web pages in the past and have had a tumultuous history with CSS... always get nervous playing around with it.

**Comment by source-toad** [comment]
Love to see it. Feel free to jump into the Obsidian discord (big ttrpg community there). If theres more features/fixes you might want. I didn't actually think there were other SWRPG GMs using this stuff :)

**Comment by Cuboos** [comment]
Yeah, i feel ya. I sorta re-fell into it a few months back searching for a good generic RPG for my own setting. Been trying to keep it alive ever since.
