### ISSUE TITLE
No Icons for Statblock

### ISSUE THREAD

**Issue by MarkThe5hark** [Craftidore/Obsidian-Genesys#11]
I have been tinkering with this for the past couple weeks. I have tried, what I feel like is everything, and I cannot get my Star Wars statblocks to look like the Acklay example you have posted here. Mostly it is just the white circular icons behind the characteristics that I cannot get to work. Not sure what I am missing or if it is an error on my behalf. Please let me know!

![Screenshot 2024-10-28 225953](https://github.com/user-attachments/assets/42bdb989-86c5-4f3a-b7b7-460bcd21728e)

**Comment by GradientForce** [comment]
How did you manage to get it to look like that? Mine currently looks like this:
![image](https://github.com/user-attachments/assets/9218d012-9443-4f6e-88cc-e2918fe61ffb)

if I could be closer to yours I'd be a hell of a lot happier with this.

**Comment by source-toad** [comment]
Hey @MarkThe5hark,

Sorry for not seeing this until several months later. The example should be the default visually as long as you've downloaded and turned on the [SWRPG Style CSS](https://github.com/Craftidore/Obsidian-Genesys/blob/master/TTRPG-Statblock-Layout/css/statblocks-swrpg-style.css), which is also available in this repository.

Give this ago and if you're still having issues, let me know!

Edit, also tagging @GradientForce as you also commented here.

**Comment by GradientForce** [comment]
Well that instantly made mine look exactly like Marks, which means I'm perfectly happy with it. Though it is missing the circles. Thank you!

**Comment by GradientForce** [comment]
Although, if you know how to make the statblock appear longer, that would be appreciated. Is there something I could throw in the markdown?
![image](https://github.com/user-attachments/assets/a40fda31-1405-466c-b471-66ba13b7d407)

**Comment by source-toad** [comment]
@MarkThe5hark @GradientForce the latest version [here](https://github.com/Craftidore/Obsidian-Genesys/blob/master/TTRPG-Statblock-Layout/css/statblocks-swrpg-style.css) should fix the issue with the circles.

In terms of length, you should be able to utilise the built in # of columns function in Fantasy Statblocks. Edit the statblock layout > Advanced > Set Columns to 1.
