### ISSUE TITLE
Issue with "Things" Theme

### ISSUE THREAD

**Issue by diegochica78** [Craftidore/Obsidian-Genesys#6]
I'm not sure if its the same for the Genesys Dice but for the Star Wars dice, the Things theme seems to break it and all the symbols become green dots.
![image](https://user-images.githubusercontent.com/98611663/168165800-e8be30d8-606c-4cf3-b547-0a1c5da3471d.png)

When in Edit mode, the dice seem normal but when in Reading mode they turn into that

**Comment by Craftidore** [comment]
Thank you so much for reporting this, and it's good to see people using my snippet! I'll try and get this fixed sometime next week.

**Comment by diegochica78** [comment]
Great Thanks a bunch!

**Comment by Craftidore** [comment]
@diegochica78 I'm tentatively going to declare this fixed with the most recent commits. I admittedly haven't tested every possible thing (like the Genesys tags inside headers), but in normal text they now work correctly in LP and Reading.
